//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_ERP_System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HM_ERP_System.ResourceCode", typeof(ResourceCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نـــرم افزار جامع مدیریت حمل و نقل ایــــــران خــــزر.
        /// </summary>
        internal static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان مورد نظر قبلا درسیستم ثبت گردید..
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان را وارد نمائید..
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا آیتم مورد نظر ازلیست حذف گردد؟.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف برای این آیتم وجود ندارد..
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شهر را وارد نمائید..
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شهر مورد نظر برای این استان قبلا درسیستم ثبت گردید..
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص را وارد نمائید..
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی شخص را وارد نمائید..
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد نمائید..
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن را وارد نمائید..
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی با این کد ملی مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام راننده مورد نظر را انتخاب نمائید..
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت را انتخاب نمائید..
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر مورد نظر را انتخاب نمائید..
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطلاعات وارد شده ثبت(ذخیره) شوند؟.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایران.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خودرو را وارد یا انتخاب نمائید..
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک ها را صحیح وارد نمائید..
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ را صحیح وارد نمائید..
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع وضعیت مالکیت را انتخاب نمائید..
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جابجایی را انتخاب نمائید..
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان بارگیری یا تخلیه را وارد نمائید..
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محل بارگیری یا تخلیه برای این نوع جابجایی قبلا در سیستم ثبت می باشد..
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالا را وارد نمائید..
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالای وارد شده تکراری می باشد..
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال پلاک را وارد نمائید..
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک وارد شده در سیستم ثبت نمی باشد..
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تمام آیتم ها را وارد نمائید..
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حواله را وارد نمائید..
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن خالص بار را وارد نمائید..
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تناژ مجازکامیون را وارد نمائید..
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک کامیون وارد شده در این تاریخ قبلا ثبت گردید. آیا موافق به ادامه ثبت عملیات می باشید؟.
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ارقام شماره کارت را کامل وارد نمائید..
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ارقام شماره شبا را کامل وارد نمائید..
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بارنامه را وارد نمائید..
        /// </summary>
        internal static string T036 {
            get {
                return ResourceManager.GetString("T036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل ثبت بارنامه برای این حواله امکان ویـــرایش وجود ندارد..
        /// </summary>
        internal static string T037 {
            get {
                return ResourceManager.GetString("T037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل ثبت بارنامه برای این حواله امکان حــــــذف وجود ندارد..
        /// </summary>
        internal static string T038 {
            get {
                return ResourceManager.GetString("T038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل صدور حواله جدید و یا عدم تحویل کالا برای این پلاک، امکان استفاده مجدد(صدور حواله جدید) از این کامیون نمی باشید..
        /// </summary>
        internal static string T039 {
            get {
                return ResourceManager.GetString("T039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا وضعیت تحویل کالاهای سطرهای انتخاب شده انجام شود؟.
        /// </summary>
        internal static string T040 {
            get {
                return ResourceManager.GetString("T040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ آیتمی از لیست انتخاب نشده است..
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف حساب را مشخص نمائید..
        /// </summary>
        internal static string T042 {
            get {
                return ResourceManager.GetString("T042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربری کامیون را مشخص نمائید..
        /// </summary>
        internal static string T043 {
            get {
                return ResourceManager.GetString("T043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطلاعات.
        /// </summary>
        internal static string T044 {
            get {
                return ResourceManager.GetString("T044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را صحیح وارد نمائید..
        /// </summary>
        internal static string T045 {
            get {
                return ResourceManager.GetString("T045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کوتاژ را وارد نمائید..
        /// </summary>
        internal static string T046 {
            get {
                return ResourceManager.GetString("T046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وزن کالای تحویلی را وارد نمائید..
        /// </summary>
        internal static string T047 {
            get {
                return ResourceManager.GetString("T047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر را انتخاب نمائید..
        /// </summary>
        internal static string T048 {
            get {
                return ResourceManager.GetString("T048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان(موضوع) فایل را وارد نمائید..
        /// </summary>
        internal static string T049 {
            get {
                return ResourceManager.GetString("T049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع(فرمت) فایل را وارد یا انتخاب نمائید..
        /// </summary>
        internal static string T050 {
            get {
                return ResourceManager.GetString("T050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل انتخاب شده از مقدار ظرفیت مجاز بیشتر می باشد..
        /// </summary>
        internal static string T051 {
            get {
                return ResourceManager.GetString("T051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک مورد نظر را انتخاب نمائید.
        /// </summary>
        internal static string T052 {
            get {
                return ResourceManager.GetString("T052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطلاعات مورد نظر حذف شوند؟.
        /// </summary>
        internal static string T053 {
            get {
                return ResourceManager.GetString("T053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر دارای مدارک پیوست می باشد. آیا با وجود مدارک حذف گردد؟.
        /// </summary>
        internal static string T054 {
            get {
                return ResourceManager.GetString("T054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری(کد ملی)  یا رمز عبور وارد شده معتبر نمیباشد..
        /// </summary>
        internal static string T055 {
            get {
                return ResourceManager.GetString("T055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری(کد ملی) را وارد نمائید..
        /// </summary>
        internal static string T056 {
            get {
                return ResourceManager.GetString("T056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور را وارد نمائید..
        /// </summary>
        internal static string T057 {
            get {
                return ResourceManager.GetString("T057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر را انتخاب نمائید..
        /// </summary>
        internal static string T058 {
            get {
                return ResourceManager.GetString("T058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربری را انتخاب نمائید..
        /// </summary>
        internal static string T059 {
            get {
                return ResourceManager.GetString("T059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T060 {
            get {
                return ResourceManager.GetString("T060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار رمز عبور وارد نمائید..
        /// </summary>
        internal static string T061 {
            get {
                return ResourceManager.GetString("T061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده با تکرار رمز عبور مغایرت دارد..
        /// </summary>
        internal static string T062 {
            get {
                return ResourceManager.GetString("T062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و رمز عبور را وارد نمائید..
        /// </summary>
        internal static string T063 {
            get {
                return ResourceManager.GetString("T063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دسترسی را انتخاب نمائید..
        /// </summary>
        internal static string T064 {
            get {
                return ResourceManager.GetString("T064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی این آیتــم به شمــا داده نشــده است.
        /// </summary>
        internal static string T065 {
            get {
                return ResourceManager.GetString("T065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دسترسی را وارد نمائید..
        /// </summary>
        internal static string T066 {
            get {
                return ResourceManager.GetString("T066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دسترسی مورد نظر قبلا ثبت گردید..
        /// </summary>
        internal static string T067 {
            get {
                return ResourceManager.GetString("T067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه حساب را انتخاب نمائید..
        /// </summary>
        internal static string T068 {
            get {
                return ResourceManager.GetString("T068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب کل را وارد نمائید..
        /// </summary>
        internal static string T069 {
            get {
                return ResourceManager.GetString("T069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کل مورد نظر برای این گروه قبلا ثبت گردید..
        /// </summary>
        internal static string T070 {
            get {
                return ResourceManager.GetString("T070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب معین را وارد نمائید..
        /// </summary>
        internal static string T071 {
            get {
                return ResourceManager.GetString("T071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب معین برای این حساب کل تکراری می باشد..
        /// </summary>
        internal static string T072 {
            get {
                return ResourceManager.GetString("T072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حســـاب را وارد نمائید..
        /// </summary>
        internal static string T073 {
            get {
                return ResourceManager.GetString("T073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب وارد شده قبلا ثبت شده است..
        /// </summary>
        internal static string T074 {
            get {
                return ResourceManager.GetString("T074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع حساب را انتخاب نمائید..
        /// </summary>
        internal static string T075 {
            get {
                return ResourceManager.GetString("T075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک آیتم را از لیست انتخاب نمائید..
        /// </summary>
        internal static string T076 {
            get {
                return ResourceManager.GetString("T076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال حـــواله سطر انتخاب شده را وارد نمائید..
        /// </summary>
        internal static string T077 {
            get {
                return ResourceManager.GetString("T077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیلی را انتخاب نمائید..
        /// </summary>
        internal static string T078 {
            get {
                return ResourceManager.GetString("T078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیلی مورد نظر قبلا ثبت گردید..
        /// </summary>
        internal static string T079 {
            get {
                return ResourceManager.GetString("T079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت سند برای حساب های یکجور امکانپذیر نمی باشد..
        /// </summary>
        internal static string T080 {
            get {
                return ResourceManager.GetString("T080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ را وارد نمائید..
        /// </summary>
        internal static string T081 {
            get {
                return ResourceManager.GetString("T081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست چند حسابی خالی می باشد..
        /// </summary>
        internal static string T082 {
            get {
                return ResourceManager.GetString("T082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بارنامه نمی تواند قبل از تاریخ حواله باشد..
        /// </summary>
        internal static string T083 {
            get {
                return ResourceManager.GetString("T083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا موافق به ادامه و ثبت حواله جدید می باشید؟.
        /// </summary>
        internal static string T084 {
            get {
                return ResourceManager.GetString("T084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار بار را وارد نمائید..
        /// </summary>
        internal static string T085 {
            get {
                return ResourceManager.GetString("T085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلمپ را وارد نمائید..
        /// </summary>
        internal static string T086 {
            get {
                return ResourceManager.GetString("T086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کرایه حمل را وارد نمائید..
        /// </summary>
        internal static string T087 {
            get {
                return ResourceManager.GetString("T087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش(بهاء) کالا را وارد نمائید..
        /// </summary>
        internal static string T088 {
            get {
                return ResourceManager.GetString("T088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارنامه نویس را انتخاب نمائید..
        /// </summary>
        internal static string T089 {
            get {
                return ResourceManager.GetString("T089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان مورد نظر قبلا انتخاب شد..
        /// </summary>
        internal static string T090 {
            get {
                return ResourceManager.GetString("T090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و ساعت را صحیح وارد نمائید..
        /// </summary>
        internal static string T091 {
            get {
                return ResourceManager.GetString("T091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست شهرها را انتخاب نمائید..
        /// </summary>
        internal static string T092 {
            get {
                return ResourceManager.GetString("T092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک مورد نظر در این تاریخ قبلا ثبت شد. آیا ثبت مجدد انجام شود؟.
        /// </summary>
        internal static string T093 {
            get {
                return ResourceManager.GetString("T093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این راننده به عنوان راننده اول انتخاب شده. امکان انتخاب برای راننده دوم وجود ندارد..
        /// </summary>
        internal static string T094 {
            get {
                return ResourceManager.GetString("T094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه را وارد نمائید..
        /// </summary>
        internal static string T095 {
            get {
                return ResourceManager.GetString("T095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه مورد نظر قبلا ثبت گردید..
        /// </summary>
        internal static string T096 {
            get {
                return ResourceManager.GetString("T096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه ها را انتخاب نمائید..
        /// </summary>
        internal static string T097 {
            get {
                return ResourceManager.GetString("T097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل بارگیری و تخلیه نمی تواند یکسان باشد..
        /// </summary>
        internal static string T098 {
            get {
                return ResourceManager.GetString("T098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مورد نظر تکراری می باشد. قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T099 {
            get {
                return ResourceManager.GetString("T099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا فرم مورد نظر بسته شود؟.
        /// </summary>
        internal static string T100 {
            get {
                return ResourceManager.GetString("T100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مورد نظر بدلیل ثبت در لیست سیاه امکان استفاده نمی باشد..
        /// </summary>
        internal static string T101 {
            get {
                return ResourceManager.GetString("T101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ یا طرف حساب پرداختی راننده به سایر را وارد نمائید..
        /// </summary>
        internal static string T102 {
            get {
                return ResourceManager.GetString("T102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره(سریال) قرارداد را وارد نمائید..
        /// </summary>
        internal static string T103 {
            get {
                return ResourceManager.GetString("T103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره(سریال) تانکر را وارد نمائید..
        /// </summary>
        internal static string T104 {
            get {
                return ResourceManager.GetString("T104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ضمانت را وارد نمائید.
        /// </summary>
        internal static string T105 {
            get {
                return ResourceManager.GetString("T105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ اجاره را وارد نمائید..
        /// </summary>
        internal static string T106 {
            get {
                return ResourceManager.GetString("T106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تانکر با این شماره قرارداد قبلا ثبت گردید..
        /// </summary>
        internal static string T107 {
            get {
                return ResourceManager.GetString("T107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع قرارداد نباید از تاریخ پایان قرارداد بیشتر یا مساوی باشد..
        /// </summary>
        internal static string T108 {
            get {
                return ResourceManager.GetString("T108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطلاعات وارد شده برای باربری مورد نظر ارسال گردد؟.
        /// </summary>
        internal static string T109 {
            get {
                return ResourceManager.GetString("T109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند حسابداری این بارنامه قبلا ثبت گردید..
        /// </summary>
        internal static string T110 {
            get {
                return ResourceManager.GetString("T110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا سند حسابداری ثبت(ذخیـــره) شود؟.
        /// </summary>
        internal static string T111 {
            get {
                return ResourceManager.GetString("T111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه را وارد نمائید..
        /// </summary>
        internal static string T112 {
            get {
                return ResourceManager.GetString("T112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه وارد شده تکراری می باشد..
        /// </summary>
        internal static string T113 {
            get {
                return ResourceManager.GetString("T113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت مورد نظر را انتخاب نمائید..
        /// </summary>
        internal static string T114 {
            get {
                return ResourceManager.GetString("T114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل ثبت سند حسابداری بارنامه مورد نظر امکان ویرایش نمی باشد..
        /// </summary>
        internal static string T115 {
            get {
                return ResourceManager.GetString("T115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده بیش از مانده حساب می باشد..
        /// </summary>
        internal static string T116 {
            get {
                return ResourceManager.GetString("T116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا توضیحات راجع به قسط را وارد نمائید..
        /// </summary>
        internal static string T117 {
            get {
                return ResourceManager.GetString("T117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارد شده معتبر نیست. تاریخ خارج از سال مالی قرار دارد..
        /// </summary>
        internal static string T118 {
            get {
                return ResourceManager.GetString("T118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات چک مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T119 {
            get {
                return ResourceManager.GetString("T119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ سندی برای این چک صادر نشده است..
        /// </summary>
        internal static string T120 {
            get {
                return ResourceManager.GetString("T120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سند یا چک را وارد نمائید. هیچ آیتمی در اسناد موقت ثبت نشده است..
        /// </summary>
        internal static string T121 {
            get {
                return ResourceManager.GetString("T121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطلاعات مورد نظر در لیست مقابل اضافه گردد؟.
        /// </summary>
        internal static string T122 {
            get {
                return ResourceManager.GetString("T122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال را صحیح وارد نمائید..
        /// </summary>
        internal static string T123 {
            get {
                return ResourceManager.GetString("T123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم های انتخاب شده در سال و ماه مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T124 {
            get {
                return ResourceManager.GetString("T124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عملیات را انتخاب نمائید..
        /// </summary>
        internal static string T125 {
            get {
                return ResourceManager.GetString("T125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام/عنوان گروه را وارد نمائید..
        /// </summary>
        internal static string T126 {
            get {
                return ResourceManager.GetString("T126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عنوان حساب معین از را انتخاب نمائید..
        /// </summary>
        internal static string T127 {
            get {
                return ResourceManager.GetString("T127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عنوان حساب معین به را انتخاب نمائید..
        /// </summary>
        internal static string T128 {
            get {
                return ResourceManager.GetString("T128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تانکر مورد نظر قبلا در سیستم ثبت گردید..
        /// </summary>
        internal static string T129 {
            get {
                return ResourceManager.GetString("T129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی را انتخاب نمائید..
        /// </summary>
        internal static string T130 {
            get {
                return ResourceManager.GetString("T130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال گواهینامه را وارد نمائید..
        /// </summary>
        internal static string T131 {
            get {
                return ResourceManager.GetString("T131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال کارت هوشمند را وارد نمائید..
        /// </summary>
        internal static string T132 {
            get {
                return ResourceManager.GetString("T132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان مورد نظر حتمـــا از لیست انتخاب شود..
        /// </summary>
        internal static string T133 {
            get {
                return ResourceManager.GetString("T133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سند با مجموع اسناد ثبت شده مغایرت دارد..
        /// </summary>
        internal static string T134 {
            get {
                return ResourceManager.GetString("T134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سند را انتخاب نمائید..
        /// </summary>
        internal static string T135 {
            get {
                return ResourceManager.GetString("T135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح قلم(توضیح) را وارد نمائید..
        /// </summary>
        internal static string T136 {
            get {
                return ResourceManager.GetString("T136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صاحب چک را وارد نمائید..
        /// </summary>
        internal static string T137 {
            get {
                return ResourceManager.GetString("T137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال چک را وارد نمائید..
        /// </summary>
        internal static string T138 {
            get {
                return ResourceManager.GetString("T138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک را وارد نمائید..
        /// </summary>
        internal static string T139 {
            get {
                return ResourceManager.GetString("T139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک موزد نظر را انتخــــاب نمائید..
        /// </summary>
        internal static string T140 {
            get {
                return ResourceManager.GetString("T140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال چک وارد شده تکراری می باشد..
        /// </summary>
        internal static string T141 {
            get {
                return ResourceManager.GetString("T141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیلی مورد نظر قبلا در لیست ثبت شده است..
        /// </summary>
        internal static string T142 {
            get {
                return ResourceManager.GetString("T142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا توضیح راجع به این سند را وارد نمائید..
        /// </summary>
        internal static string T143 {
            get {
                return ResourceManager.GetString("T143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری(شخص) مورد نظر در حساب مقابل قرار دارد. امکان سند جابجایی برای این مشتری(شخص) مقدور نمی باشید..
        /// </summary>
        internal static string T144 {
            get {
                return ResourceManager.GetString("T144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو حساب انتخاب شده نمی تواند یکی باشد..
        /// </summary>
        internal static string T145 {
            get {
                return ResourceManager.GetString("T145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال(فیش) را وارد نمائید..
        /// </summary>
        internal static string T146 {
            get {
                return ResourceManager.GetString("T146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه را وارد نمائید..
        /// </summary>
        internal static string T147 {
            get {
                return ResourceManager.GetString("T147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک و شعبه وارد شده تکراری می باشد..
        /// </summary>
        internal static string T148 {
            get {
                return ResourceManager.GetString("T148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر بدلیل پیوست(ثبت مدارک) امکان حذف نمی باشد..
        /// </summary>
        internal static string T149 {
            get {
                return ResourceManager.GetString("T149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مانده ابتدای دوره حذف گردد؟.
        /// </summary>
        internal static string T150 {
            get {
                return ResourceManager.GetString("T150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا موافقید از برنامه(نــرم افزار) خارج شوید..
        /// </summary>
        internal static string T151 {
            get {
                return ResourceManager.GetString("T151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک و شعبه را انتخـــاب نمائید..
        /// </summary>
        internal static string T152 {
            get {
                return ResourceManager.GetString("T152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پورسانت را انتخاب نمائید..
        /// </summary>
        internal static string T153 {
            get {
                return ResourceManager.GetString("T153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال بارنامه تکراری می باشد..
        /// </summary>
        internal static string T154 {
            get {
                return ResourceManager.GetString("T154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل ثبت سند حسابداری بارنامه مورد نظر امکان حذف نمی باشد..
        /// </summary>
        internal static string T155 {
            get {
                return ResourceManager.GetString("T155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب را وارد نمائید..
        /// </summary>
        internal static string T156 {
            get {
                return ResourceManager.GetString("T156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی وارد شده تکراری می باشد..
        /// </summary>
        internal static string T157 {
            get {
                return ResourceManager.GetString("T157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست ستونهای حذف شده.
        /// </summary>
        internal static string T158 {
            get {
                return ResourceManager.GetString("T158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گـــزارش   از تاریــخ: .
        /// </summary>
        internal static string T159 {
            get {
                return ResourceManager.GetString("T159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تـــا تاریـــخ: .
        /// </summary>
        internal static string T160 {
            get {
                return ResourceManager.GetString("T160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست نوبت دهی کامیـــون ها.
        /// </summary>
        internal static string TRappointmentScheduling {
            get {
                return ResourceManager.GetString("TRappointmentScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کامیــــون ها.
        /// </summary>
        internal static string TRcars {
            get {
                return ResourceManager.GetString("TRcars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست بارنامــــه ها.
        /// </summary>
        internal static string TRcomerB {
            get {
                return ResourceManager.GetString("TRcomerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست حـــواله ها.
        /// </summary>
        internal static string TRcomerH {
            get {
                return ResourceManager.GetString("TRcomerH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پورســــانت ها.
        /// </summary>
        internal static string TRCommission {
            get {
                return ResourceManager.GetString("TRCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اشخـــــاص.
        /// </summary>
        internal static string TRcustomer {
            get {
                return ResourceManager.GetString("TRcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست حســـــاب های تفصیلی.
        /// </summary>
        internal static string TRdataileAccounts {
            get {
                return ResourceManager.GetString("TRdataileAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست راننـــــده ها.
        /// </summary>
        internal static string TRdraver {
            get {
                return ResourceManager.GetString("TRdraver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انبارهای بارگیری و تخلیه.
        /// </summary>
        internal static string TRplaseTransfer {
            get {
                return ResourceManager.GetString("TRplaseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کـــــالاها.
        /// </summary>
        internal static string TRproduct {
            get {
                return ResourceManager.GetString("TRproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست خرید تانکرها.
        /// </summary>
        internal static string TRPurchase_Tanker {
            get {
                return ResourceManager.GetString("TRPurchase_Tanker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست همه حســــــاب ها.
        /// </summary>
        internal static string TRreviewAccountsAllAcconts {
            get {
                return ResourceManager.GetString("TRreviewAccountsAllAcconts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست حســـــاب های تفصیلی.
        /// </summary>
        internal static string TRreviewAccountsD {
            get {
                return ResourceManager.GetString("TRreviewAccountsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست گــــروه حسابها.
        /// </summary>
        internal static string TRreviewAccountsG {
            get {
                return ResourceManager.GetString("TRreviewAccountsG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گــزارش صورتحســـــاب.
        /// </summary>
        internal static string TRreviewAccountsList {
            get {
                return ResourceManager.GetString("TRreviewAccountsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیســت حســـــاب های معیــــــن.
        /// </summary>
        internal static string TRreviewAccountsS {
            get {
                return ResourceManager.GetString("TRreviewAccountsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست حســــــاب های کــــــل.
        /// </summary>
        internal static string TRreviewAccountsT {
            get {
                return ResourceManager.GetString("TRreviewAccountsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنـــــــــــد.
        /// </summary>
        internal static string TRreviewAccountsTransaction {
            get {
                return ResourceManager.GetString("TRreviewAccountsTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اجـــاره تانکـــرها.
        /// </summary>
        internal static string TRtankerRental {
            get {
                return ResourceManager.GetString("TRtankerRental", resourceCulture);
            }
        }
    }
}
